
--require("nvim-tree").setup({
--    disable_netrw = true,
--    hijack_netrw = true,
--    modified = {
--        enable = true,
--        show_on_dirs = true,
--    },
--    renderer = {
--        icons = {
--            glyphs = {
--                modified = "*",
--            },
--        },
--        indent_markers = {
--            enable = true,
--        },
--    },
--})
--
